# Generated by Django 4.2 on 2023-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackflow_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_reports/')),
            ],
        ),
    ]
